# Generated by Django 3.2.3 on 2021-05-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=191)),
                ('order_qty', models.CharField(max_length=191)),
                ('order_sales', models.FloatField()),
                ('order_ship_mode', models.CharField(choices=[('Regular Air', 'Regular Air'), ('Delivery Truck', 'Delivery Truck'), ('Express Air', 'Express Air')], max_length=50)),
                ('order_profit', models.FloatField()),
                ('order_unit_price', models.FloatField()),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_date_new', models.CharField(blank=True, max_length=50, null=True)),
                ('order_customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('order_customer_segment', models.CharField(blank=True, max_length=50, null=True)),
                ('order_product_category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
